package app

const (
	Gpt3_5 = "gpt-3.5-turbo"
	Gpt4   = "gpt-4"
)

var Languages = map[string][]string{
	"af": {"Afrikaans", Gpt3_5},
	"sq": {"Shqip", Gpt3_5},
	"ar": {"العربية", Gpt4},
	"hy": {"Հայերեն", Gpt4},
	"bn": {"বাংলা", Gpt4},
	"bs": {"Bosanski", Gpt3_5},
	"bg": {"Български", Gpt4},
	"ca": {"Català", Gpt3_5},
	"hr": {"Hrvatski", Gpt3_5},
	"cs": {"Čeština", Gpt3_5},
	"da": {"Dansk", Gpt3_5},
	"nl": {"Nederlands", Gpt3_5},
	"en": {"English", Gpt3_5},
	"eo": {"Esperanto", Gpt3_5},
	"et": {"Eesti", Gpt3_5},
	"tl": {"Filipino", Gpt4},
	"fi": {"Suomi", Gpt3_5},
	"fr": {"Français", Gpt3_5},
	"de": {"Deutsch", Gpt3_5},
	"el": {"Ελληνικά", Gpt3_5},
	"gu": {"ગુજરાતી", Gpt4},
	"hi": {"हिन्दी", Gpt4},
	"hu": {"Magyar", Gpt3_5},
	"is": {"Íslenska", Gpt3_5},
	"id": {"Bahasa Indonesia", Gpt3_5},
	"it": {"Italiano", Gpt3_5},
	"ja": {"日本語", Gpt4},
	"jw": {"Basa Jawa", Gpt4},
	"ko": {"한국어", Gpt3_5},
	"la": {"Latina", Gpt3_5},
	"lv": {"Latviešu", Gpt3_5},
	"lt": {"Lietuvių", Gpt3_5},
	"ml": {"മലയാളം", Gpt4},
	"mr": {"मराठी", Gpt4},
	"no": {"Norsk", Gpt3_5},
	"pl": {"Polski", Gpt3_5},
	"pt": {"Português", Gpt3_5},
	"pa": {"ਪੰਜਾਬੀ", Gpt4},
	"ro": {"Română", Gpt3_5},
	"ru": {"Русский", Gpt3_5},
	"sr": {"Српски", Gpt3_5},
	"sk": {"Slovenčina", Gpt3_5},
	"sl": {"Slovenščina", Gpt3_5},
	"es": {"Español", Gpt3_5},
	"sw": {"Kiswahili", Gpt4},
	"sv": {"Svenska", Gpt3_5},
	"ta": {"தமிழ்", Gpt4},
	"te": {"తెలుగు", Gpt4},
	"th": {"ไทย", Gpt3_5},
	"tr": {"Türkçe", Gpt3_5},
	"uk": {"Українська", Gpt3_5},
	"ur": {"اردو", Gpt4},
	"vi": {"Tiếng Việt", Gpt3_5},
	"cy": {"Cymraeg", Gpt4},
	"he": {"עברית", Gpt3_5},
	"mk": {"Македонски", Gpt3_5},
}
