package app

const (
	Gpt3_5 = "gpt-3.5-turbo"
	Gpt4   = "gpt-4"
)

var Languages = map[string][]string{
	"af": {"Afrikaans", Gpt3_5},
	"sq": {"Albanian", Gpt3_5},
	"ar": {"Arabic", Gpt4},
	"hy": {"Armenian", Gpt4},
	"bn": {"Bengali", Gpt4},
	"bs": {"Bosnian", Gpt3_5},
	"bg": {"Bulgarian", Gpt4},
	"ca": {"Catalan", Gpt3_5},
	"hr": {"Croatian", Gpt3_5},
	"cs": {"Czech", Gpt3_5},
	"da": {"Danish", Gpt3_5},
	"nl": {"Dutch", Gpt3_5},
	"en": {"English", Gpt3_5},
	"eo": {"Esperanto", Gpt3_5},
	"et": {"Estonian", Gpt3_5},
	"tl": {"Filipino", Gpt4},
	"fi": {"Finnish", Gpt3_5},
	"fr": {"French", Gpt3_5},
	"de": {"German", Gpt3_5},
	"el": {"Greek", Gpt3_5},
	"gu": {"Gujarati", Gpt4},
	"hi": {"Hindi", Gpt4},
	"hu": {"Hungarian", Gpt3_5},
	"is": {"Icelandic", Gpt3_5},
	"id": {"Indonesian", Gpt3_5},
	"it": {"Italian", Gpt3_5},
	"ja": {"Japanese", Gpt4},
	"jw": {"Javanese", Gpt4},
	"ko": {"Korean", Gpt3_5},
	"la": {"Latin", Gpt3_5},
	"lv": {"Latvian", Gpt3_5},
	"lt": {"Lithuanian", Gpt3_5},
	"ml": {"Malayalam", Gpt4},
	"mr": {"Marathi", Gpt4},
	"no": {"Norwegian", Gpt3_5},
	"pl": {"Polish", Gpt3_5},
	"pt": {"Portuguese", Gpt3_5},
	"pa": {"Punjabi", Gpt4},
	"ro": {"Romanian", Gpt3_5},
	"ru": {"Russian", Gpt3_5},
	"sr": {"Serbian", Gpt3_5},
	"sk": {"Slovak", Gpt3_5},
	"sl": {"Slovenian", Gpt3_5},
	"es": {"Spanish", Gpt3_5},
	"sw": {"Swahili", Gpt4},
	"sv": {"Swedish", Gpt3_5},
	"ta": {"Tamil", Gpt4},
	"te": {"Telugu", Gpt4},
	"th": {"Thai", Gpt3_5},
	"tr": {"Turkish", Gpt3_5},
	"uk": {"Ukrainian", Gpt3_5},
	"ur": {"Urdu", Gpt4},
	"vi": {"Vietnamese", Gpt3_5},
	"cy": {"Welsh", Gpt4},
	"he": {"Hebrew", Gpt3_5},
	"mk": {"Macedonian", Gpt3_5},
}
