package app

var Languages = map[string]string{
	"af": "Afrikaans",
	"sq": "Shqip",
	"ar": "العربية",
	"hy": "Հայերեն",
	"bn": "বাংলা",
	"bs": "Bosanski",
	"bg": "Български",
	"ca": "Català",
	"hr": "Hrvatski",
	"cs": "Čeština",
	"da": "Dansk",
	"nl": "Nederlands",
	"en": "English",
	"eo": "Esperanto",
	"et": "Eesti",
	"tl": "Filipino",
	"fi": "Suomi",
	"fr": "Français",
	"de": "Deutsch",
	"el": "Ελληνικά",
	"gu": "ગુજરાતી",
	"hi": "हिन्दी",
	"hu": "Magyar",
	"is": "Íslenska",
	"id": "Bahasa Indonesia",
	"it": "Italiano",
	"ja": "日本語",
	"jw": "Basa Jawa",
	"km": "ភាសាខ្មែរ",
	"ko": "한국어",
	"la": "Latina",
	"lv": "Latviešu",
	"lt": "Lietuvių",
	"ml": "മലയാളം",
	"mr": "मराठी",
	"my": "မြန်မာ",
	"ne": "नेपाली",
	"no": "Norsk",
	"pl": "Polski",
	"pt": "Português",
	"pa": "ਪੰਜਾਬੀ",
	"ro": "Română",
	"ru": "Русский",
	"sr": "Српски",
	"si": "සිංහල",
	"sk": "Slovenčina",
	"sl": "Slovenščina",
	"es": "Español",
	"su": "Basa Sunda",
	"sw": "Kiswahili",
	"sv": "Svenska",
	"ta": "தமிழ்",
	"te": "తెలుగు",
	"th": "ไทย",
	"tr": "Türkçe",
	"uk": "Українська",
	"ur": "اردو",
	"vi": "Tiếng Việt",
	"cy": "Cymraeg",
	"xh": "IsiXhosa",
	"yi": "ייִדיש",
	"zu": "IsiZulu",
	"am": "አማርኛ",
	"az": "Azərbaycanca",
	"be": "Беларуская",
	"eu": "Euskara",
	"gl": "Galego",
	"ha": "Hausa",
	"ht": "Kreyòl Ayisyen",
	"ka": "ქართული",
	"kn": "ಕನ್ನಡ",
	"mg": "Malagasy",
	"ps": "پښتو",
	"qu": "Qhichwa",
	"oc": "Occitan",
	"ga": "Gaeilge",
	"he": "עברית",
	"mk": "Македонски",
}
